{{- if .Values.api.enabled -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "postcodes-io.api.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "postcodes-io.api.name" . }}
    helm.sh/chart: {{ include "postcodes-io.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
data:
  defaults.js: |-
    module.exports = {{ toJson .Values.api.defaults }};
{{- end }}
