apiVersion: v1
kind: Secret
metadata:
  name: {{ include "postcodes-io.database.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "postcodes-io.database.name" . }}
    helm.sh/chart: {{ include "postcodes-io.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
type: Opaque
data:
  password: {{ .Values.database.password | b64enc }}
