apiVersion: v1
kind: Service
metadata:
  name: {{ include "postcodes-io.database.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "postcodes-io.database.name" . }}
    helm.sh/chart: {{ include "postcodes-io.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  type: {{ .Values.database.service.type }}
  ports:
    - port: {{ .Values.database.service.port }}
      targetPort: postgres
      protocol: TCP
      name: postgres
  selector:
    app.kubernetes.io/name: {{ include "postcodes-io.database.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
